### ISSUE TITLE
Curtain draws over selected item so it's invisible.

### ISSUE THREAD

**Issue by AndriiUhryn** [AigeStudio/WheelPicker#119]
Can you draw curtain under items so they will be visible? Or if it's already implemented than how to use it ??

**Comment by comm1x** [comment]
Have the same problem. Want to use colorPrimary as curtain, and.. it fully overlapped selected item. So I need to use whole black (#000) text color, and curtain with alpha channel.
This is some bullshit. I dont know how much developers should have been drunk to do this.

**Comment by d745282469** [comment]
Do you fix it?

**Comment by d745282469** [comment]
> Can you draw curtain under items so they will be visible? Or if it's already implemented than how to use it ??

Draw curtain before loop.
