### ISSUE TITLE
WheelCurvedPicker 调用setItemIndex()方法 界面错乱

### ISSUE THREAD

**Issue by lesliesam** [AigeStudio/WheelPicker#14]
使用WheelCurvedPicker，在没有上下滑动过的时候调用setItemIndex没有问题，但是有过上下滑动之后再调用就会出现乱跳现象。

经过debug发现unitDeltaTotal变量没有制空导致的，所以我试了复写setItemIndex方法就好了。
@Override
    public void setItemIndex(int index) {
        super.setItemIndex(index);
        unitDeltaTotal = 0;
    }

WheelCurvedPicker具体逻辑看上去非常复杂，不是很了解，所以没有提Pull request。

**Comment by qqnp1100** [comment]
楼上NB,我也发现这个bug，不过看了半天代码不知道怎么解决。。。

**Comment by GeorgeBin** [comment]
使用WheelCurvedPicker，调用setItemIndex，得到的数据和index都是对的，但是UI上并没有变动，始终是停留在第一个，请问是我哪方面做的不对吗?怎么解决?

**Comment by LNeway** [comment]
@lesliesam 按照你所说的方法改了以后界面还是会有错乱的情况。

**Comment by lesliesam** [comment]
@LNeway 你是在WheelCurvedPicker类里面重载了这个方法吗？我这里改了就好了。

**Comment by LNeway** [comment]
@lesliesam 嗯，是的，我用两个滚轮做了一个省市级联的选择，就是选择重庆的时候，另外一个滚轮出现了问题，其他的省市都没问题，蛋疼。

**Comment by lesliesam** [comment]
@LNeway 问题解决了吗？你需要我帮你看下代码不？

**Comment by LNeway** [comment]
@lesliesam 这个控件现在暂时不用了，就不麻烦您了 ，谢谢您的热心^_^

**Comment by SSSSHIELD** [comment]
@lesliesam 多谢指教，这个问题困扰了我好久，曾经一度换成了WheelStraightPicker.....复写并置空之后，问题得到解决，thx

**Comment by lesliesam** [comment]
@SSSSHIELD 不客气啦，很高兴能帮到你。

**Comment by pengbs** [comment]
@lesliesam 厉害，解决了我的问题，非常感谢

**Comment by pengbs** [comment]
@lesliesam 现在发现个bug，你这样处理在控件上显示确实没问题，但是onWheelSelected得到的数据还是之前的，这个时候滑动一下就正常了，你知道是什么原因吗？

**Comment by lesliesam** [comment]
@pengbs 不客气，你也很牛啊，这个都被你找出来了。

**Comment by MrSunly** [comment]
@pengbs 按照你的方法重写setItemIndex之后在大部分手机上都运行正常，但是在华为EMUI3.0和Emotion2.3手机上setItemIndex执行之后onWheelSelected已经成功回调但是view没有变化，必须手动点击一下才会变化

**Comment by cdkd123** [comment]
WheelCurvedPicker 这个类被移除了？
