### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by DeevD** [AigeStudio/WheelPicker#151]
How to disable Loop for item?

**Comment by AigeStudio** [comment]
Use XML attribute "wheel_cyclic" or method "setCyclic" in WheelPicker.

**Comment by DeevD** [comment]
thank a lot bro

**Comment by DeevD** [comment]
another is indicator with item text padding change?

**Comment by AigeStudio** [comment]
nope, If you want to change text padding which in the middle of indicator, you can use "setItemSpace" method to change item space. Indicator will recompute its position right between items once item space changed.

绘制指示器不会改变文本内边距。如果你想增加中间数据项的文本与指示器之间的间隔，可以考虑使用“setItemSpace”方法增加数据项之间的间隔。增加数据项之间的间隔会导致数据项的高度变大，从而迫使指示器重新计算它的位置使自己绘制在两个数据项正中间。
