### ISSUE TITLE
建议不要使用enum

### ISSUE THREAD

**Issue by Piasy** [AigeStudio/WheelPicker#2]
安卓上尽量不要使用enum，可以结合`@IntDef`注解，使用int定义常量。

**Comment by AigeStudio** [comment]
虽然Colt和Romain都有在IO和Talk上说避免在Android中使用枚举，但是我个人觉得在一些非常驻的情况下使用少量的枚举类型并无大的影响。不过你得建议很好，我会在下个版本使用int定义常量行为，不过不会考虑依赖注解

**Comment by Piasy** [comment]
依赖注解有什么问题吗？使用`@IntDef`之后，IDE可以对代码进行检查，避免调用的时候传错参数。

**Comment by AigeStudio** [comment]
没有问题，只是不想在lib module里二次依赖任何三方框架 ^_^
