### ISSUE TITLE
Make addLable Public in DatePicker to customize Lables. 

### ISSUE THREAD

**Issue by bliveinhack** [AigeStudio/WheelPicker#23]
can you please make addlabel public or something more custmisable to allow developer change DatePicker label to English or something else.
![2016-06-22 13_58_12-genymotion for personal use - custom phone - 5 1 0 - api 22 - 768x1280 1440x256](https://cloud.githubusercontent.com/assets/2360658/16259707/91babfde-3881-11e6-968b-4aa832824483.png)

**Comment by AigeStudio** [comment]
I'm afraid you can do that because widget under package curved is only use for show you how to use WheelCurvedPicker

**Comment by bliveinhack** [comment]
i have made my own DatePicker class with some minor modification to your DatePicker class. and able to change label.

i think you just need to remove hardcoded string to user define string via setters method. that will help non Chinese developer to use your DatePicker class. 
Thanks.

**Comment by AigeStudio** [comment]
I'm modifying this project for more better function, it will be easier to use.

**Comment by bliveinhack** [comment]
That's great. :+1: 
Here is my customized class for quick fix: https://gist.github.com/bliveinhack/1017ad72747395aead61d186e29a2bbc
