### ISSUE TITLE
setCurrentItem(#) not giving me particular position and not being called second time.

### ISSUE THREAD

**Issue by ccrazycoder** [AigeStudio/WheelPicker#27]
I've tested below scenario on your latest demo 1.1.0.

I've array of 20. What I need is if User select position 2 then I want spinner to rotate to 3rd position.
So onItemSelected callback I've written as below. 

> 	public void onItemSelected(WheelPicker picker, Object data, int position) {
>         String text = "";
>         switch (picker.getId()) {
>             case R.id.main_wheel_left:
>                 if (position == 2)
>                 {
>                     wheelLeft.setCurrentItem(1);
>                 }
>                 text = "Left: " + position + " :: ";
>                 break;
>             case R.id.main_wheel_center:
>                 text = "Center:";
>                 break;
>             case R.id.main_wheel_right:
>                 text = "Right:";
>                 break;
>         }
>         Toast.makeText(this, text + String.valueOf(data), Toast.LENGTH_SHORT).show();
>     }

	
I'm stuck with Two Issues. It's not sending me to 1st position on call of setCurrentItem(1) and this condition not working
for second time.

**Comment by AigeStudio** [comment]
In fact, this is a incomplete feature in 1.1.0, i will finish in next few days and merge to master branch.

**Comment by ccrazycoder** [comment]
Yes I've updated your branch.. and its working in my case now. 
When you are planning to Trunk merge..

**Comment by AigeStudio** [comment]
I will merge to master after a while, but it can't compile from JCenter yet, i change the group id and wait for JFrog update reply.
