### ISSUE TITLE
WheelPicker最后一个数据滑出屏幕不会自动回滚，一个WheelPicker数量超过24个的时候无法选中后面的

### ISSUE THREAD

**Issue by caiyoufei** [AigeStudio/WheelPicker#29]
1.当手指滑动WheelPicker时，在不设置无限滚动的情况下，将最后一个数据滑出屏幕，不会自动回滚到选中最后一条
2.一个WheelPicker不设置无限滚动，设置的数据超过24个后，继续往上滑动，会自动回滚到第23的位置(从0-23)，当设置无限滚动后没有该问题

**Comment by 531227501** [comment]
动态设置data就会发生问题2.
步骤为, 首先set长度为24的list,  然后在set长度为30的list, 之后滚动到25-30之间的位置时, 会自动回滚到24的位置.
请尽快检查修复一下.

**Comment by AigeStudio** [comment]
1.1.1发布了、你看看解决你那个问题没

**Comment by 531227501** [comment]
未能在1.1.1中重现该问题, 该问题已被修复, thx.

**Comment by damathryx** [comment]
I'm getting this problem with v1.1.2

**Comment by nimatrueway** [comment]
I also got this problem with v1.1.2 too. (I'm using [ReactNativeWheelPicker](https://github.com/ElekenAgency/ReactNativeWheelPicker) wrapper by the way)
Invoking setSelectedItemPosition with any value above >24 will set position to 24.
