### ISSUE TITLE
当wheel的data为空时,滑动会崩溃.

### ISSUE THREAD

**Issue by mudao** [AigeStudio/WheelPicker#41]
`08-31 10:05:22.225 4814-4814/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: cn.area, PID: 4814
                                                 java.lang.ArithmeticException: divide by zero
                                                     at smartcity.view.WheelPicker.WheelPicker.run(WheelPicker.java:781)`

建议在run()方法中先检查data的是否有数据再执行滑动.
`  @Override
    public void run() {
        _if(mData==null || mData.size()<=0){
            return;
        }_
        if (mScroller.isFinished() && !isForceFinishScroll  ) {
                           ....
     }}`

**Comment by AigeStudio** [comment]
做了处理、不过我很好奇这是在什么情况下触发的……

**Comment by AigeStudio** [comment]
这个问题不是数据为空的问题，而是WheelPicker在添加到某些开源控件中时，父布局尺寸变更后并没有迫使子元素的尺寸变更，所以WheelPicker无法计算到布局改变后的高度

**Comment by mudao** [comment]
我是做了二级地区二级联动.像香港澳门这种就没有二级子城市.有一个wheelPicker数据size就0.手指划到二级wheelPicker就会触发run().
