### ISSUE TITLE
setdata()之后不会自动回滚

### ISSUE THREAD

**Issue by xushaun** [AigeStudio/WheelPicker#8]
我设置一个size为10的data，然后滚动到第8个，然后再设置size为3的data，然后设置setIndex为0，但是wheelpicker没有回滚，要我手动滑动才能看到新设置的数据，请问当第二次数据少于前一次数据的时候，怎么样才能让wheelpicker能重新最新数据(不需要手动滑动)

**Comment by AigeStudio** [comment]
你怎么设置的？我通过线程或回调事件设置都可以被刷新：

```Java
        new Thread(new Runnable() {
            @Override
            public void run() {
                SystemClock.sleep(3000);
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        final List<String> newData = new ArrayList<>();
                        newData.add("AigeStudio");
                        newData.add("Fuck");
                        newData.add("Bull shit");
                        straightPicker.setData(newData);
                        straightPicker.setItemIndex(0);
                    }
                });
            }
        }).start();
```

点击事件：
```Java
            case R.id.main_obtain_straight_btn:
                final List<String> newData = new ArrayList<>();
                newData.add("AigeStudio");
                newData.add("Fuck");
                newData.add("Bull shit");
                straightPicker.setData(newData);
                straightPicker.setItemIndex(0);
                break;
```

**Comment by xushaun** [comment]
很感谢您的答复，其实我是要做省市2级滚动，当省变化时我需要更改city的data
但是代码如下实现确实如我所说，不能正确显示

cityList是个2维列表
province.setOnWheelChangeListener(new OnWheelChangeListener() {

			@Override
			public void onWheelSelected(int index, String data) {
				// TODO Auto-generated method stub
				city.setData(cityList.get(index));
				city.setItemIndex(0);
	

			}
                     ....
}

**Comment by AigeStudio** [comment]
= = 不会吧，数据没问题么，你可以参考WheelDatePicker日期选择这个控件，跟省市区联动逻辑是一致的，只是数据不同而已，WheelDatePicker在滑动后会根据不同的月份显示不同的天数，因为每个月天数不是相同的

**Comment by xushaun** [comment]
WheelDatePicker在滑动后会根据不同的月份显示不同的天数，能麻烦你帮我找找关键代码吗，我也一直在找从31天切换到30天的月份后picker会自动切换回去，我代码大概看了下，原以为是因为DayPicker调用了init方法，但是试了下Init打方法还是没有效果

**Comment by AigeStudio** [comment]
WheelDayPicker里面setCurrentYearAndMonth方法：
```Java
    public void setCurrentYearAndMonth(int year, int month) {
        setYear(year);
        setMonth(month);
        initData();
        checkScrollState();
    }
```
checkScrollState

**Comment by xushaun** [comment]
这个方法我试过了
@Override
			public void onWheelSelected(int index, String data) {
				// TODO Auto-generated method stub
				city.clearCache();
				
				city.setData(cityList.get(index));
				city.setItemIndex(0);
				//city.checkScrollState();
				//city.requestLayout();
				Log.i("test", "province index is " + index);
				Log.i("test", "province data is " + data);

			}
这些我全试了，还是不行，可以的话，我想把源代码Demo给你，你帮我看看，如果你有空的话，留个邮箱给我，我发demo给你

**Comment by AigeStudio** [comment]
aigestudio@qq.com

**Comment by xushaun** [comment]
感谢您的帮助，当我在准备Demo的时候，我又尝试了下，发现的2个问题解决了
1：当第一次的的数据源size大于第二次的数据源size时，可能会出现数据显示不出来，checkScrollState可以解决这个问题
2：有时候数据源切换的时候，pick不会自动刷新，显示的还是原来的数据，需要点击picker才会显示最新的数据，手动调用invalidate可以解决

以下代码尝试过，没有问题，再次感谢您的帮助

province.setOnWheelChangeListener(new OnWheelChangeListener() {

			@Override
			public void onWheelSelected(int index, String data) {
				// TODO Auto-generated method stub
				city.setData(cityList.get(index));
				city.setItemIndex(0);
				city.checkScrollState();
				city.invalidate();
			}
